;list is like((name dd mm yyyy) (name dd mm yyyy) .......)
(define (valid_name_date ls2)
     (cond ((null? ls2) '())
           ((eq? (date_vality (cdar ls2)) #t) (cons (car ls2) (valid_name_date (cdr ls2))))
           ((eq? (date_vality (cdar ls2)) #f) (valid_name_date (cdr ls2)))
           (else (valid_name_date (cdr ls2)))))
           
;list is like(dd mm yyyy)
(define (date_vality ls1)
       (cond ((or (< (caddr ls1) 1) (< (cadr ls1) 1) (> (cadr ls1) 12) (< (car ls1) 0) 
                  (> (car ls1) 31)) #f)
             ((and (or (= (cadr ls1) 1) (= (cadr ls1) 3) (= (cadr ls1) 5) (= (cadr ls1) 7) 
                   (= (cadr ls1) 8) (= (cadr ls1) 10) (= (cadr ls1) 12))) #t)
             ((and (or (= (cadr ls1) 4) (= (cadr ls1) 6) (= (cadr ls1) 9) (= (cadr ls1) 11)) 
                   (< (car ls1) 31)) #t)
             ((and (= (cadr ls1) 2)
                   (or (= (remainder (caddr ls1) 400) 0) 
                   (and  (= (remainder (caddr ls1) 4) 0) (not (= (remainder (caddr ls1) 100) 0))))
                   (< (car ls1) 30)) #t)
             ((and (= (cadr ls1) 2) (< (car ls1) 29)) #t)
             (else #f)))
             

